
package com.dasanzhone.namespace.deviceservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.dasanzhone.namespace.deviceservice.general.DeviceInformationReturn;
import com.dasanzhone.namespace.deviceservice.general.DeviceReturn;
import com.dasanzhone.namespace.deviceservice.general.ForecastRequest;
import com.dasanzhone.namespace.deviceservice.general.ForecastReturn;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeviceService", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/")
@XmlSeeAlso({
    com.dasanzhone.namespace.deviceservice.datatypes.ObjectFactory.class,
    com.dasanzhone.namespace.deviceservice.exception.ObjectFactory.class,
    com.dasanzhone.namespace.deviceservice.general.ObjectFactory.class,
    org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface DeviceService {


    /**
     * Gets Information for each DeviceID
     * 
     * @param zip
     * @return
     *     returns com.dasanzhone.namespace.deviceservice.general.DeviceInformationReturn
     * @throws DeviceException
     */
    @WebMethod(operationName = "GetDeviceInformation", action = "http://www.dasanzhone.com/namespace/deviceservice/GetDeviceInformation")
    @WebResult(name = "GetDeviceInformationResult", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
    @RequestWrapper(localName = "GetDeviceInformation", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetDeviceInformation")
    @ResponseWrapper(localName = "GetDeviceInformationResponse", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetDeviceInformationResponse")
    public DeviceInformationReturn getDeviceInformation(
        @WebParam(name = "ZIP", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
        String zip)
        throws DeviceException
    ;

    /**
     * Allows you to get your City Forecast Over the Next 7 Days, which is updated hourly.
     * 
     * @param forecastRequest
     * @return
     *     returns com.dasanzhone.namespace.deviceservice.general.ForecastReturn
     * @throws DeviceException
     */
    @WebMethod(operationName = "GetCityForecastByZIP", action = "http://www.dasanzhone.com/namespace/deviceservice/GetCityForecastByZIP")
    @WebResult(name = "GetCityForecastByZIPResult", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
    @RequestWrapper(localName = "GetCityForecastByZIP", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetCityForecastByZIP")
    @ResponseWrapper(localName = "GetCityForecastByZIPResponse", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetCityForecastByZIPResponse")
    public ForecastReturn getCityForecastByZIP(
        @WebParam(name = "ForecastRequest", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
        ForecastRequest forecastRequest)
        throws DeviceException
    ;

    /**
     * Allows you to get your City's Device, which is updated hourly.
     * 
     * @param forecastRequest
     * @return
     *     returns com.dasanzhone.namespace.deviceservice.general.DeviceReturn
     * @throws DeviceException
     */
    @WebMethod(operationName = "GetCityDeviceByZIP", action = "http://www.dasanzhone.com/namespace/deviceservice/GetCityDeviceByZIP")
    @WebResult(name = "GetCityDeviceByZIPResult", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
    @RequestWrapper(localName = "GetCityDeviceByZIP", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetCityDeviceByZIP")
    @ResponseWrapper(localName = "GetCityDeviceByZIPResponse", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general", className = "com.dasanzhone.namespace.deviceservice.general.GetCityDeviceByZIPResponse")
    public DeviceReturn getCityDeviceByZIP(
        @WebParam(name = "ForecastRequest", targetNamespace = "http://www.dasanzhone.com/namespace/deviceservice/general")
        ForecastRequest forecastRequest)
        throws DeviceException
    ;

}
